[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 2000
fs_permissions = [{ access = "read-write", path = "./out"}]

[profile.local]
eth_rpc_url = "http://localhost:8545"

[profile.testnet]
eth_rpc_url = "https://testnet-rpc.monad.xyz"

[dependencies]
"forge-std" = "1.9.6"
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.2.0"

[rpc_endpoints]
anvil = "http://localhost:8545"
monad_testnet = "https://testnet-rpc.monad.xyz"
