[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 2000
fs_permissions = [{ access = "read-write", path = "./out" }]

[profile.local]
eth_rpc_url = "http://localhost:8545"

[profile.testnet]
eth_rpc_url = "https://testnet-rpc.monad.xyz"

[profile.tn2]
eth_rpc_url = "https://rpc-testnet-2.monadinfra.com"

[profile.mainnet]
eth_rpc_url = "https://rpc-mainnet.monadinfra.com"

[dependencies]
"forge-std" = "1.10.0"
"@openzeppelin-contracts" = "5.4.0"
"@openzeppelin-contracts-upgradeable" = "5.4.0"

[rpc_endpoints]
anvil = "http://localhost:8545"
monad_testnet = "https://testnet-rpc.monad.xyz"
monad_testnet2 = "https://rpc-testnet-2.monadinfra.com"
monad_mainnet = "https://rpc-mainnet.monadinfra.com"
